# Generated by Django 2.2.2 on 2019-06-16 19:48

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=200, unique=True),
        ),
    ]
